version: "3.8"

services:
  backend:
    build: ./backend
    container_name: devops-backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - ./backend/urls.db:/app/urls.db
    environment:
      - SHORT_BASE=http://localhost:4000
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: devops-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE=http://localhost:4000
      - VITE_FRONTEND_BASE=http://localhost:5173
    restart: unless-stopped
